#
# Turn off hall lights when no motions detected after 1 minute.
# Eteindre les lumières du hall quand il n'y a plus de mouvements détectés dans le hall.
#
alias: motion_off_hall
trigger:
  platform: state
  entity_id: binary_sensor.tradfri_motion_sensor_2
  to: 'off'
  for:
    minutes: 1
action:
  service: light.turn_off
  entity_id: light.hall_2