alias: off_forced_hall
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    event: 2003
    id: tradfri_on_off_switch_hall_2
action:
  - service: light.turn_off
    entity_id: light.hall_2
  - service: automation.turn_on
    entity_id: automation.motion_off_hall