#
# Trun on the kitchen light with a ON short press on a Tradfri remote.
# Allumer la lumière de la cuisine avec un appuis court sur le boutton ON d'une télécommande Tradfri.
#
alias: all_off
description: ''
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    event: 1002
    id: tradfri_on_off_switch_cuisine
condition: []
action:
- service: light.turn_on
  data:
    entity_id: light.lustre_cuisine
    brightness: 254