#
# Trying to start playlist on volumio in my son's bedroom for the evening song but it dosen't work for now.
# J'essaye de lancer un playlist sur volumio dans la chambre de mon fils pour les veilleuses du soir mais ça ne fontionne pas pour l'instant.
#
alias: evening Jules playlist
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    event: 5002
    id: tradfri_remote_control_ch_jules
condition: []
action:
  - service: media_player.select_source
    entity_id: media_player.spotify_pasoad
    data:
      source: Volumiojules_2
  - service: media_player.play_media
    entity_id: media_player.spotify_pasoad
    data:
      media_content_type: playlist
      media_content_id: spotify:playlist:3w0JBF4naOiTSc85H73Mtw
