alias: pause volumio chambre de Jules
description: ''
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    event: 5003
    id: tradfri_remote_control_ch_jules
condition: []
action:
  - service: media_player.media_pause
    entity_id: media_player.volumiojules_3