#
# Automatically power off the volumio player (with a Tradfri switch) in my son's bedroom at 21:30 when we are at home.
# Eteindre automatiquement le player volumio (avec un switch Tradfri) dans la chambre de mon fils à 21:30 quand nous sommes chez nous.
#
alias: "radio_off"
trigger:
  - platform: time
    at: '21:30:00'
condition:
  condition: state
  entity_id: group.potellefamily
  state: home
action:
  - service: switch.turn_off
    entity_id: switch.on_off_radio_de_jules