alias: back_home_light
trigger:
  - platform: state
    entity_id: group.potellefamily
    from: away
    to: not_home
condition:
  - condition: state
    entity_id: sensor.daylight
    state: golden_hour_2
action:
  - service: light.turn_on
    entity_id: light.petites_lumieres_2
