alias: Update Available Notification
trigger:
  platform: state
  entity_id: binary_sensor.updater
condition:
  condition: template
  value_template: "{{ (states('sensor.current_version') != states('sensor.latest_version')) }}"
action:
  - service: notify.mobile_app_iphone_de_p_a
    data_template:
      title: Upgrade time!
      message: "HA version {{ (states('sensor.latest_version')) }} is available!"
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: "HA version {{ (states('sensor.latest_version')) }} is available!"