alias: "guest_mode_sat_ios_yes"
initial_state: true
hide_entity: true
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: 'GUEST_MODE_YES'
action:
- service: input_boolean.turn_on
  entity_id: input_boolean.guest_mode