alias: chauffage_off
description: ''
trigger:
  - device_id: 42cc01f317a04062a1a234adb0ee3697
    domain: binary_sensor
    entity_id: binary_sensor.window_door_sensor
    platform: device
    type: opened
action:
  - service: switch.turn_off
    entity_id: switch.on_off_salle_de_bain
  # - service: automation.turn_on
  #   entity_id: automation.turn_off_spot_salle_de_bain_8_to_17
  # - service: automation.turn_on
  #   entity_id: automation.turn_off_spot_salle_de_bain_17_to_22
  # - service: automation.turn_on
  #   entity_id: automation.turn_off_spot_salle_de_bain_22_to_8