alias: turn_off_spot
trigger:
  platform: state
  entity_id: binary_sensor.tradfri_motion_sensor
  to: 'off'
  for:
    minutes: 1
condition:
- condition: device
  device_id: 42cc01f317a04062a1a234adb0ee3697
  domain: binary_sensor
  entity_id: binary_sensor.window_door_sensor
  type: is_open
action:
  service: light.turn_off
  entity_id: light.salle_de_bain_2