alias: eteindre_la_tv_salon
description: ''
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    event: 2002
    id: on_off_switch_chambre_parents
condition: []
action:
- service: script.turn_on
  entity_id: script.eteindre_tv